CREATE MATERIALIZED VIEW FG_FORMELEMENTINFOATMETA_MV
REFRESH FORCE ON DEMAND
AS
SELECT t."FORMCODE",t."ENTITYIMPCODE",t."ELEMENTCLASS",t."DISPLAYLABEL",t."ISPARENTPATHID",t."ADDITIONALDATA",t."ISHIDDEN",
       t."ISSEARCHIDHOLDER",t."FORMCODEENTITYLABEL",t."FORMCODETYPLABEL",max(distinct t.islistid) over (partition by formcode_entity, entityimpcode) as "ISLISTID", t."ISSEARCHELEMENT",
       f."FORMCODE_ENTITY", t.datatype, t.datatype_info
FROM FG_FORMELEMENTINFOATMETA_TMP t,
     fg_form f
where t.formcode = f.formcode;
