create materialized view FG_S_EXPERIMENTSELECT_ALL_MV
refresh force on demand
as
WITH SELECT_VIEW AS
  (SELECT t.*,
          regexp_substr(t.EXPERIMENT_ID, '[^,]+', 1, commas.column_value) AS single_val
   FROM FG_S_EXPERIMENTSELECT_V t,
        table(cast(multiset
                     (SELECT LEVEL
                      FROM dual CONNECT BY LEVEL <= LENGTH (regexp_replace(t.EXPERIMENT_ID, '[^,]+')) + 1) AS sys.OdciNumberList)) commas)
SELECT distinct --SELECT_VIEW.* without single_val
      SELECT_VIEW."EXPERIMENTSELECT_ID",SELECT_VIEW."FORM_TEMP_ID",SELECT_VIEW."EXPERIMENTSELECT_OBJIDVAL",SELECT_VIEW."FORMID",SELECT_VIEW."TIMESTAMP",SELECT_VIEW."CLONEID",SELECT_VIEW."TEMPLATEFLAG",SELECT_VIEW."CHANGE_BY",SELECT_VIEW."SESSIONID",SELECT_VIEW."ACTIVE",SELECT_VIEW."FORMCODE_ENTITY",SELECT_VIEW."FORMCODE",SELECT_VIEW."PARENTID",SELECT_VIEW."EXPERIMENTSELECTNAME",SELECT_VIEW."DISABLED",SELECT_VIEW."EXPERIMENT_ID"
      ,ex.EXPERIMENTNAME ,ex.EXPERIMENT_ID as singleExp_id
FROM SELECT_VIEW,
     fg_s_experiment_v ex
WHERE SELECT_VIEW.single_val = ex.EXPERIMENT_ID
AND SELECT_VIEW.single_val <> 'null'
AND SELECT_VIEW.single_val IS NOT NULL;
