create or replace view fg_s_invitemmaterial_all_v as
select t."INVITEMMATERIAL_ID",t."FORM_TEMP_ID",t."INVITEMMATERIAL_OBJIDVAL",t."FORMID",t."TIMESTAMP",t."CREATION_DATE",t."CLONEID",t."TEMPLATEFLAG",t."CHANGE_BY",t."CREATED_BY",t."SESSIONID",t."ACTIVE",t."FORMCODE_ENTITY",t."FORMCODE",t."LASTNORMALDENSITY",t."AUHZ",t."XCOORDINATEINMATRIX",t."CHEMICALFORMULA",t."COMMENTS",t."MW_UOM_ID",t."BATCHES",t."HAZARDCODES",t."MINSTOCKLEVEL_UOM_ID",t."COMPONENTS",t."RISKCODES",t."CATEGORY_ID",t."SPECTRUM",t."VISCOSITY",t."MANUFACTURER_ID",t."MATERIALFUNC_ID",t."FORMNUMBERID",t."PROJECT_ID",t."CASNAME",t."MW",t."ITEMID",t."COFORMULANT",t."ALTERNATIVECOFORMULANTS",t."ALTERNATIVEGROUP",t."MATERIALPROTOCOLTYPE",t."MATERIALTYPE_ID",t."DENSITY",t."QUANTITY_UOM_ID",t."SYNONYMSADAPTED",t."MSDS",t."BOILINGPOINT",t."SYNONYMS",t."MELTINGPOINT",t."MATERIALFORM",t."MELTINGPOINT_UOM",t."VISCOSITY_UOM_ID",t."DESCRIPTION",t."PH",t."MATERIALAPPEARANCE",t."MINSTOCKLEVEL",t."INVITEMMATERIALNAME",t."CASNUMBER",t."MATERIALSEARCHRETURNJSON",t."YCOORDINATEINMATRIX",t."CASNUMBUTTON",t."BOILINGPOINT_UOM",t."DENSITY_UOM_ID",t."STRUCTURE",t."IUPACNAME",t."QUANTITY",t."STORAGECONDITION",t."STATUS_ID",t."TRAINING",t."SOURCEPROJECTID",t."RECIPEFORMULATION_ID"
--t.* end! edit only the code below...
,f.MATERIALFUNCTIONNAME,cd.mol_data as "MOL", CD.SMILES_DATA AS "SMILES", CD.INCHI_DATA as "INCHI", st.MaterialStatusName,
(select LISTAGG( mt.MATERIALTYPENAME, ',') WITHIN GROUP (ORDER BY mt.MATERIALTYPENAME)
from  fg_s_materialtype_all_v mt
where instr(','||t.MATERIALTYPE_ID||',', ','||mt.MATERIALTYPE_ID||',')>0) as MATERIALTYPENAME,
(select LISTAGG( p.PROJECTNAME, ',') WITHIN GROUP (ORDER BY p.PROJECTNAME)
from  fg_s_project_all_v p
where instr(','||t.project_id||',', ','||p.PROJECT_ID||',')>0) as PROJECTNAME,m.MANUFACTURERNAME
from FG_S_INVITEMMATERIAL_V t, FG_CHEM_DOODLE_DATA cd, fg_s_materialstatus_v st,fg_s_manufacturer_v m,fg_s_materialfunction_v f
where t.STRUCTURE = cd.parent_id(+)
and t.MANUFACTURER_ID = m.MANUFACTURER_ID(+)
and t.STATUS_ID = st.materialstatus_id(+)
and t.MATERIALFUNC_ID= f.FORMID(+)
