create or replace view fg_s_document_all_v as
select t."DOCUMENT_ID",t."FORM_TEMP_ID",t."DOCUMENT_OBJIDVAL",t."FORMID",t."TIMESTAMP",t."CREATION_DATE",t."CLONEID",t."TEMPLATEFLAG",t."CHANGE_BY",t."CREATED_BY",t."SESSIONID",t."ACTIVE",t."FORMCODE_ENTITY",t."FORMCODE",t."LINK_ATTACHMENT",t."DOCUMENTUPLOAD",t."CONTENTCHANGE",t."PARENTID",t."SAMPLE_ID",t."DOCUMENTNAME",t."DESCRIPTION",t."TABLETYPE"
--t.* end! edit only the code below...
,t1.FILE_NAME, t1.file_display_id, t1.FILE_CHEM_ID ,t1.CONTENT_TYPE as FILE_CONTENT_TYPE_
from FG_S_DOCUMENT_V t,
     FG_FILES_FAST_V t1
     where t."DOCUMENTUPLOAD" = t1.FILE_ID(+);
